#!/usr/local/bin/python3

VERSION = 20150101

MINIMUM_OUTPUT_PREDICATE_WEIGHT         = 3
MINIMUM_UNIGRAM_WORD_SHARES             = 2
MINIMUM_DEFINITION_PREDICT_WEIGHT       = 1
MINIMUM_UNIGRAM_MATCH_PER_DEFINITION    = 2
